theme: minima

title: Kazeshinu's Autopoké
description: > # this means to ignore newlines until "show_excerpts:"
  Autopoke is an set of automation scripts for pokeclicker.
  Including autoclicker, autobreeding and other features

show_excerpts: false

author: Kazeshinu

github_username: Kazeshinu

url-pretty: "https://github.com/Kazeshinu/Autopoke"

keywords: "pokeclicker,script,helper,autoclicker,automatic,breeding,hatching,dungeon"

google_analytics: "G-W9TN9CGVMN"

minima:
  skin: dark
  
header_pages:
  - index.md
  - infopages/breeding.md
  - infopages/clicking.md
  - infopages/dungeon.md
  - infopages/farming.md
  - infopages/gym.md
  - infopages/underground.md

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

