remote_theme: jekyll/minima

title: Kazeshinu's Autopoké
description: > # this means to ignore newlines until "show_excerpts:"
  Autopoke is an set of automation scripts for pokeclicker.
  Including autoclicker, autobreeding and other features

show_excerpts: false

author:
  name: Kazeshinu

url-pretty: "https://github.com/Kazeshinu/Autopoke"

keywords: "pokeclicker,script,helper,autoclicker,automatic,breeding,hatching,dungeon"

google_analytics: "G-W9TN9CGVMN"

minima:
  skin: solarized-dark
   social_links:
    - { platform: github, user_url: "https://github.com/Kazeshinu/" }

header_pages:
  - index.md
  - infopages/breeding.md
  - infopages/clicking.md
  - infopages/dungeon.md
  - infopages/farming.md
  - infopages/gym.md
  - infopages/underground.md
  - infopages/quests.md

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

